"""init

Revision ID: 85b4660d3edc
Revises: 
Create Date: 2026-01-06 09:55:42.622949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b4660d3edc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_mode', sa.Boolean(), nullable=False),
    sa.Column('primary_key_name', sa.String(), nullable=False),
    sa.Column('sort_key_name', sa.String(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('key_condition', sa.Text(), nullable=True),
    sa.Column('filter_conditions', sa.Text(), nullable=False),
    sa.Column('next_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_table('saved_queries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_mode', sa.Boolean(), nullable=False),
    sa.Column('primary_key_name', sa.String(), nullable=False),
    sa.Column('sort_key_name', sa.String(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('key_condition', sa.Text(), nullable=True),
    sa.Column('filter_conditions', sa.Text(), nullable=False),
    sa.Column('next_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_created_at'), 'saved_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_queries_name'), 'saved_queries', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_queries_name'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_created_at'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_query_history_created_at'), table_name='query_history')
    op.drop_table('query_history')
    # ### end Alembic commands ###
