on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  ouput-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry install
      - run: poetry export -f requirements.txt -o requirements.txt
      - uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements.txt


  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    needs: ouput-requirements
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-20.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: requirements
          path: requirements.txt
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: org.flatpak.dyna_cli.yaml
          bundle: dyna_cli.flatpak
          build-bundle: true
          cache-key: flatpak-builder-${{ github.sha }}
