on:
  release:
    types: [published]
name: flatpak builder
jobs:
  ouput-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry install
      - run: poetry export -f requirements.txt -o requirements.txt
      - uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements.txt
      - uses: actions/upload-artifact@v3
        with:
            name: requirements
            path: requirements.txt

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    needs: ouput-requirements
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-20.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: requirements
          path: build
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          manifest-path: org.flatpak.dyno-viewer.yaml
          bundle: dyno-viewer.flatpak
          build-bundle: true
          cache-key: flatpak-builder
          gpg-sign: 482D785950010673538143D76E5AC8BB1FA09156
      - uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          file: dyno-viewer.flatpak
          tag: ${{ github.ref }}
          asset_name: ${{ runner.arch }}-$tag-dyno-viewer.flatpak
        