name: publish pip package
on:
    release:
      types: [published]
jobs:
  publish-python-package:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: parse-version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: poetry install
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: version
        run: poetry version "$VERSION"
      - run: poetry publish --build

